import Head from 'next/head';
import {useRouter} from 'next/router';
import {Grid, Button} from '@material-ui/core';
import SwapCard from '../components/swapCard';
import InfoCard from '../components/infoCard';

export default function Home() {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Atari Decentralized Exchange</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/token/ATARI.png" />
      </Head>

      <div className = "diceGrid1">
        {/* <Grid container className = "text-center mb-5">
          <Grid item xs = {1} sm = {2} md = {4}></Grid>
          <Grid item xs = {10} sm = {8} md = {4} className = "x-home-top-container">
          <Button variant = "outlined" className = "x-home-top-button " onClick = {()=>router.push("/swap")}>Swap</Button>
            <Button variant = "outlined" className = "x-home-top-button " onClick = {()=>router.push("/liquidity")}>Liquidity</Button>
            <Button variant = "outlined" className = "x-home-top-button " onClick = {()=>router.push("/stake")}>Stake</Button>
            <Button variant = "outlined" className = "x-home-top-button " onClick = {()=>router.push("/buy")}>Buy</Button>
          </Grid>
          <Grid item xs = {1} sm = {2} md = {4}></Grid>
        </Grid> */}
        <Grid container>
          <Grid item xs = {1} sm = {1} md = {1}></Grid>
          <Grid item xs = {12} sm = {12} md = {10}>
            <SwapCard />
            {/* <div className = "mt-4">
              <InfoCard />
            </div> */}
          </Grid>
          <Grid item xs = {1} sm = {1} md = {1}></Grid>
        </Grid>
      </div>
    </div>
  )
}
